# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  # ワークスペースごとではなく、ルートだけを対象にする。
  # https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    # 同じバージョン番号で同時に更新する必要がある依存関係だけを列挙する。
    # @fastify のように所有者が共通するだけの依存関係は対象外とする。
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      slacc:
        patterns:
          - 'slacc-*'
      storybook:
        patterns:
          - 'storybook*'
          - '@storybook/*'
