[install]
linker = "isolated"
saveTextLockfile = true
auto = "disable"
exact = true
minimumReleaseAge = 604800

minimumReleaseAgeExcludes = [
	"@misskey-dev/emoji-assets",
	"@misskey-dev/emoji-data",
	"@misskey-dev/sharp-read-bmp",
	"@syuilo/aiscript",
	"mfm-js",
	"slacc",
	"vite",
]
