[install]
linker = "isolated"
saveTextLockfile = true
auto = "disable"
exact = true
minimumReleaseAge = 604800

minimumReleaseAgeExcludes = [
	"@misskey-dev/browser-image-resizer",
	"@misskey-dev/emoji-assets",
	"@misskey-dev/emoji-data",
	"@misskey-dev/sharp-read-bmp",
	"@misskey-dev/summaly",
	"@syuilo/aiscript",
	"buraha",
	"mfm-js",
	"slacc",
	"slacc-android-arm-eabi",
	"slacc-android-arm64",
	"slacc-darwin-arm64",
	"slacc-darwin-universal",
	"slacc-darwin-x64",
	"slacc-freebsd-x64",
	"slacc-linux-arm-gnueabihf",
	"slacc-linux-arm64-gnu",
	"slacc-linux-arm64-musl",
	"slacc-linux-x64-gnu",
	"slacc-linux-x64-musl",
	"slacc-win32-arm64-msvc",
	"slacc-win32-x64-msvc",
	"@typescript/native-preview",
	"vite",
]
