/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Signer {
  static fromPkcs8Der(suite: SignatureAlgorithm, der: Buffer): Signer
  static fromPkcs8Pem(suite: SignatureAlgorithm, pem: string): Signer
  get publicKey(): Buffer
  signParts(parts: Array<Buffer>, callback: ((err: Error | null, arg: Buffer) => any)): void
  signRaw(payload: Buffer, callback: ((err: Error | null, arg: Buffer) => any)): void
}

export declare class Verifier {
  static fromSpkiDer(suite: SignatureAlgorithm, der: Buffer): Verifier
  static fromSpkiPem(suite: SignatureAlgorithm, pem: string): Verifier
  verifyParts(signature: Buffer, parts: Array<Buffer>, callback: ((err: Error | null, arg: boolean) => any)): void
  verifyRaw(signature: Buffer, payload: Buffer, callback: ((err: Error | null, arg: boolean) => any)): void
}

export declare class ZipReader {
  static withDestinationPath(path: string): ZipReader
  viaBuffer(buffer: Buffer): void
}

export declare function init(numThreads: number): void

export declare const enum SignatureAlgorithm {
  Mldsa44 = 'Mldsa44',
  Eddsa = 'Eddsa',
  Rsa2048_8192 = 'Rsa2048_8192'
}
