/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Signer {
  static fromPkcs8Der(suite: SignatureAlgorithm, der: Buffer): Signer
  static fromPkcs8Pem(suite: SignatureAlgorithm, pem: string): Signer
  get publicKey(): Buffer
  signParts(parts: Array<Buffer>, callback: ((err: Error | null, arg: Buffer) => any)): void
  signRaw(payload: Buffer, callback: ((err: Error | null, arg: Buffer) => any)): void
}

export declare class Verifier {
  static fromSpkiDer(suite: SignatureAlgorithm, der: Buffer): Verifier
  static fromSpkiPem(suite: SignatureAlgorithm, pem: string): Verifier
  verifyParts(signature: Buffer, parts: Array<Buffer>, callback: ((err: Error | null, arg: boolean) => any)): void
  verifyRaw(signature: Buffer, payload: Buffer, callback: ((err: Error | null, arg: boolean) => any)): void
}

/**
 * アップロードされた zip から、名前を指定した通常ファイルだけをメモリへ読む。
 * ディスクへは展開しない。エントリ名に含まれるパスや symlink を辿る余地を残さないため。
 */
export declare class ZipArchiveReader {
  static fromBuffer(buffer: Buffer): ZipArchiveReader
  /**
   * `name` と完全一致するエントリの中身を返す。無ければ null。
   * ディレクトリ・symlink・暗号化されたエントリと、展開後に `max_bytes` を超えるエントリはエラーにする。
   * 宣言サイズは偽れるので、実際に読んだバイト数でも上限を確かめる。
   */
  readFile(name: string, maxBytes: number): Buffer | null
}

export declare function init(numThreads: number): void

export declare const enum SignatureAlgorithm {
  Mldsa44 = 'Mldsa44',
  Eddsa = 'Eddsa',
  Rsa2048_8192 = 'Rsa2048_8192'
}
