include:
  - ./compose.a.yml
  - ./compose.b.yml

services:
  setup:
    extends:
      file: ./compose.tpl.yml
      service: misskey
    command: >
      bash -c "
        bun install --frozen-lockfile
      "

  tester:
    image: oven/bun:${BUN_VERSION}-debian
    depends_on:
      a.test:
        condition: service_healthy
      misskey.a.test:
        condition: service_healthy
      b.test:
        condition: service_healthy
      misskey.b.test:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/rootCA.crt
    volumes:
      - type: bind
        source: ../package.json
        target: /misskey/packages/backend/package.json
        read_only: true
      - type: bind
        source: ../../frontend-shared/package.json
        target: /misskey/packages/frontend-shared/package.json
        read_only: true
      - type: bind
        source: ../../frontend/package.json
        target: /misskey/packages/frontend/package.json
        read_only: true
      - type: bind
        source: ../../frontend-builder/package.json
        target: /misskey/packages/frontend-builder/package.json
        read_only: true
      - type: bind
        source: ../../frontend-embed/package.json
        target: /misskey/packages/frontend-embed/package.json
        read_only: true
      - type: bind
        source: ../test/resources
        target: /misskey/packages/backend/test/resources
        read_only: true
      - type: bind
        source: ./test
        target: /misskey/packages/backend/test-federation/test
        read_only: true
      - type: bind
        source: ../vitest.config.ts
        target: /misskey/packages/backend/vitest.config.ts
        read_only: true
      - type: bind
        source: ../vitest.config.fed.ts
        target: /misskey/packages/backend/vitest.config.fed.ts
        read_only: true
      - type: bind
        source: ../scripts/compile_config.js
        target: /misskey/packages/backend/scripts/compile_config.js
        read_only: true
      - type: bind
        source: ../../icons-subsetter/package.json
        target: /misskey/packages/icons-subsetter/package.json
        read_only: true
      - type: bind
        source: ../../aiscript-languageserver-stub/package.json
        target: /misskey/packages/aiscript-languageserver-stub/package.json
        read_only: true
      - type: bind
        source: ../../sw/package.json
        target: /misskey/packages/sw/package.json
        read_only: true
      - type: bind
        source: ../../misskey-js/built
        target: /misskey/packages/misskey-js/built
        read_only: true
      - type: bind
        source: ../../misskey-js/package.json
        target: /misskey/packages/misskey-js/package.json
        read_only: true
      - type: bind
        source: ../../misskey-js/generator/package.json
        target: /misskey/packages/misskey-js/generator/package.json
        read_only: true
      - type: bind
        source: ../../i18n/built
        target: /misskey/packages/i18n/built
        read_only: true
      - type: bind
        source: ../../i18n/package.json
        target: /misskey/packages/i18n/package.json
        read_only: true
      - type: bind
        source: ../../../package.json
        target: /misskey/package.json
        read_only: true
      - type: bind
        source: ../../../scripts/changelog-checker/package.json
        target: /misskey/scripts/changelog-checker/package.json
        read_only: true
      - type: bind
        source: ../../../bun.lock
        target: /misskey/bun.lock
        read_only: true
      - type: bind
        source: ../../../bunfig.toml
        target: /misskey/bunfig.toml
        read_only: true
      - type: bind
        source: ../../../patches
        target: /misskey/patches
        read_only: true
      - type: bind
        source: ./certificates/rootCA.crt
        target: /usr/local/share/ca-certificates/rootCA.crt
        read_only: true
    working_dir: /misskey
    entrypoint: >
      bash -c '
        bun install --frozen-lockfile
        exec "$0" "$@"
      '
    command: bun run --bun --filter backend test:fed

  daemon:
    image: oven/bun:${BUN_VERSION}-debian
    depends_on:
      redis.test:
        condition: service_healthy
    volumes:
      - type: bind
        source: ../package.json
        target: /misskey/packages/backend/package.json
        read_only: true
      - type: bind
        source: ../../frontend-shared/package.json
        target: /misskey/packages/frontend-shared/package.json
        read_only: true
      - type: bind
        source: ../../frontend/package.json
        target: /misskey/packages/frontend/package.json
        read_only: true
      - type: bind
        source: ../../frontend-builder/package.json
        target: /misskey/packages/frontend-builder/package.json
        read_only: true
      - type: bind
        source: ../../frontend-embed/package.json
        target: /misskey/packages/frontend-embed/package.json
        read_only: true
      - type: bind
        source: ../../i18n/package.json
        target: /misskey/packages/i18n/package.json
        read_only: true
      - type: bind
        source: ../../icons-subsetter/package.json
        target: /misskey/packages/icons-subsetter/package.json
        read_only: true
      - type: bind
        source: ../../aiscript-languageserver-stub/package.json
        target: /misskey/packages/aiscript-languageserver-stub/package.json
        read_only: true
      - type: bind
        source: ../../sw/package.json
        target: /misskey/packages/sw/package.json
        read_only: true
      - type: bind
        source: ../../misskey-js/package.json
        target: /misskey/packages/misskey-js/package.json
        read_only: true
      - type: bind
        source: ../../misskey-js/generator/package.json
        target: /misskey/packages/misskey-js/generator/package.json
        read_only: true
      - type: bind
        source: ./daemon.ts
        target: /misskey/packages/backend/test-federation/daemon.ts
        read_only: true
      - type: bind
        source: ./tsconfig.json
        target: /misskey/packages/backend/test-federation/tsconfig.json
        read_only: true
      - type: bind
        source: ../../../package.json
        target: /misskey/package.json
        read_only: true
      - type: bind
        source: ../../../scripts/changelog-checker/package.json
        target: /misskey/scripts/changelog-checker/package.json
        read_only: true
      - type: bind
        source: ../../../bun.lock
        target: /misskey/bun.lock
        read_only: true
      - type: bind
        source: ../../../bunfig.toml
        target: /misskey/bunfig.toml
        read_only: true
      - type: bind
        source: ../../../patches
        target: /misskey/patches
        read_only: true
    working_dir: /misskey
    command: >
      bash -c "
        bun install --frozen-lockfile
        bun run --bun tsgo -p ./packages/backend/test-federation
        bun ./packages/backend/test-federation/built/daemon.js
      "

  redis.test:
    image: redis:7-alpine
    volumes:
      - type: bind
        source: ./volumes/redis
        target: /data
        bind:
          create_host_path: true
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 20
