/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/*
 * Consolidated endpoint metadata assembly.
 * Key order below MUST stay sorted by UTF-16 code unit order (the order the
 * legacy `import * as` module-namespace object exposed) — it determines the
 * endpoint ordering of the public /api.json document.
 */
import { endpointMetas as adminMetas } from './metas/admin.js';
import { endpointMetas as adminAbuseReportMetas } from './metas/admin-abuse-report.js';
import { endpointMetas as adminEmojiMetas } from './metas/admin-emoji.js';
import { endpointMetas as adminQueueMetas } from './metas/admin-queue.js';
import { endpointMetas as adminRolesMetas } from './metas/admin-roles.js';
import { endpointMetas as adminSystemWebhookMetas } from './metas/admin-system-webhook.js';
import { endpointMetas as antennasMetas } from './metas/antennas.js';
import { endpointMetas as channelsMetas } from './metas/channels.js';
import { endpointMetas as chartsMetas } from './metas/charts.js';
import { endpointMetas as chatMetas } from './metas/chat.js';
import { endpointMetas as clipsMetas } from './metas/clips.js';
import { endpointMetas as driveMetas } from './metas/drive.js';
import { endpointMetas as federationMetas } from './metas/federation.js';
import { endpointMetas as flashMetas } from './metas/flash.js';
import { endpointMetas as followingMetas } from './metas/following.js';
import { endpointMetas as galleryMetas } from './metas/gallery.js';
import { endpointMetas as hashtagsMetas } from './metas/hashtags.js';
import { endpointMetas as iMetas } from './metas/i.js';
import { endpointMetas as miscMetas } from './metas/misc.js';
import { endpointMetas as notesMetas } from './metas/notes.js';
import { endpointMetas as pagesMetas } from './metas/pages.js';
import { endpointMetas as usersMetas } from './metas/users.js';

const endpointMetaGroups = [
	adminMetas,
	adminAbuseReportMetas,
	adminEmojiMetas,
	adminQueueMetas,
	adminRolesMetas,
	adminSystemWebhookMetas,
	antennasMetas,
	channelsMetas,
	chartsMetas,
	chatMetas,
	clipsMetas,
	driveMetas,
	federationMetas,
	flashMetas,
	followingMetas,
	galleryMetas,
	hashtagsMetas,
	iMetas,
	miscMetas,
	notesMetas,
	pagesMetas,
	usersMetas,
] as const;

export const endpointMetas = {
	'admin/abuse-report/notification-recipient/create': adminAbuseReportMetas['admin/abuse-report/notification-recipient/create'],
	'admin/abuse-report/notification-recipient/delete': adminAbuseReportMetas['admin/abuse-report/notification-recipient/delete'],
	'admin/abuse-report/notification-recipient/list': adminAbuseReportMetas['admin/abuse-report/notification-recipient/list'],
	'admin/abuse-report/notification-recipient/show': adminAbuseReportMetas['admin/abuse-report/notification-recipient/show'],
	'admin/abuse-report/notification-recipient/update': adminAbuseReportMetas['admin/abuse-report/notification-recipient/update'],
	'admin/abuse-user-reports': adminMetas['admin/abuse-user-reports'],
	'admin/accounts/create': adminMetas['admin/accounts/create'],
	'admin/accounts/delete': adminMetas['admin/accounts/delete'],
	'admin/accounts/find-by-email': adminMetas['admin/accounts/find-by-email'],
	'admin/ad/create': adminMetas['admin/ad/create'],
	'admin/ad/delete': adminMetas['admin/ad/delete'],
	'admin/ad/list': adminMetas['admin/ad/list'],
	'admin/ad/update': adminMetas['admin/ad/update'],
	'admin/announcements/create': adminMetas['admin/announcements/create'],
	'admin/announcements/delete': adminMetas['admin/announcements/delete'],
	'admin/announcements/list': adminMetas['admin/announcements/list'],
	'admin/announcements/update': adminMetas['admin/announcements/update'],
	'admin/avatar-decorations/create': adminMetas['admin/avatar-decorations/create'],
	'admin/avatar-decorations/delete': adminMetas['admin/avatar-decorations/delete'],
	'admin/avatar-decorations/list': adminMetas['admin/avatar-decorations/list'],
	'admin/avatar-decorations/update': adminMetas['admin/avatar-decorations/update'],
	'admin/captcha/current': adminMetas['admin/captcha/current'],
	'admin/captcha/save': adminMetas['admin/captcha/save'],
	'admin/delete-account': adminMetas['admin/delete-account'],
	'admin/delete-all-files-of-a-user': adminMetas['admin/delete-all-files-of-a-user'],
	'admin/drive/clean-remote-files': adminMetas['admin/drive/clean-remote-files'],
	'admin/drive/cleanup': adminMetas['admin/drive/cleanup'],
	'admin/drive/files': adminMetas['admin/drive/files'],
	'admin/drive/show-file': adminMetas['admin/drive/show-file'],
	'admin/emoji/add': adminEmojiMetas['admin/emoji/add'],
	'admin/emoji/add-aliases-bulk': adminEmojiMetas['admin/emoji/add-aliases-bulk'],
	'admin/emoji/copy': adminEmojiMetas['admin/emoji/copy'],
	'admin/emoji/delete': adminEmojiMetas['admin/emoji/delete'],
	'admin/emoji/delete-bulk': adminEmojiMetas['admin/emoji/delete-bulk'],
	'admin/emoji/import-zip': adminEmojiMetas['admin/emoji/import-zip'],
	'admin/emoji/list': adminEmojiMetas['admin/emoji/list'],
	'admin/emoji/list-remote': adminEmojiMetas['admin/emoji/list-remote'],
	'admin/emoji/remove-aliases-bulk': adminEmojiMetas['admin/emoji/remove-aliases-bulk'],
	'admin/emoji/set-aliases-bulk': adminEmojiMetas['admin/emoji/set-aliases-bulk'],
	'admin/emoji/set-category-bulk': adminEmojiMetas['admin/emoji/set-category-bulk'],
	'admin/emoji/set-license-bulk': adminEmojiMetas['admin/emoji/set-license-bulk'],
	'admin/emoji/update': adminEmojiMetas['admin/emoji/update'],
	'admin/federation/delete-all-files': adminMetas['admin/federation/delete-all-files'],
	'admin/federation/refresh-remote-instance-metadata': adminMetas['admin/federation/refresh-remote-instance-metadata'],
	'admin/federation/remove-all-following': adminMetas['admin/federation/remove-all-following'],
	'admin/federation/update-instance': adminMetas['admin/federation/update-instance'],
	'admin/forward-abuse-user-report': adminMetas['admin/forward-abuse-user-report'],
	'admin/get-index-stats': adminMetas['admin/get-index-stats'],
	'admin/get-table-stats': adminMetas['admin/get-table-stats'],
	'admin/get-user-ips': adminMetas['admin/get-user-ips'],
	'admin/invite/create': adminMetas['admin/invite/create'],
	'admin/invite/list': adminMetas['admin/invite/list'],
	'admin/meta': adminMetas['admin/meta'],
	'admin/promo/create': adminMetas['admin/promo/create'],
	'admin/queue/abandon-outbox-dead-letter': adminQueueMetas['admin/queue/abandon-outbox-dead-letter'],
	'admin/queue/clear': adminQueueMetas['admin/queue/clear'],
	'admin/queue/deliver-delayed': adminQueueMetas['admin/queue/deliver-delayed'],
	'admin/queue/inbox-delayed': adminQueueMetas['admin/queue/inbox-delayed'],
	'admin/queue/jobs': adminQueueMetas['admin/queue/jobs'],
	'admin/queue/outbox-dead-letters': adminQueueMetas['admin/queue/outbox-dead-letters'],
	'admin/queue/pause': adminQueueMetas['admin/queue/pause'],
	'admin/queue/promote-jobs': adminQueueMetas['admin/queue/promote-jobs'],
	'admin/queue/queue-stats': adminQueueMetas['admin/queue/queue-stats'],
	'admin/queue/queues': adminQueueMetas['admin/queue/queues'],
	'admin/queue/remove-job': adminQueueMetas['admin/queue/remove-job'],
	'admin/queue/resume': adminQueueMetas['admin/queue/resume'],
	'admin/queue/retry-job': adminQueueMetas['admin/queue/retry-job'],
	'admin/queue/retry-outbox-dead-letter': adminQueueMetas['admin/queue/retry-outbox-dead-letter'],
	'admin/queue/show-job': adminQueueMetas['admin/queue/show-job'],
	'admin/queue/show-job-logs': adminQueueMetas['admin/queue/show-job-logs'],
	'admin/queue/stats': adminQueueMetas['admin/queue/stats'],
	'admin/relays/add': adminMetas['admin/relays/add'],
	'admin/relays/list': adminMetas['admin/relays/list'],
	'admin/relays/remove': adminMetas['admin/relays/remove'],
	'admin/reset-password': adminMetas['admin/reset-password'],
	'admin/resolve-abuse-user-report': adminMetas['admin/resolve-abuse-user-report'],
	'admin/roles/assign': adminRolesMetas['admin/roles/assign'],
	'admin/roles/create': adminRolesMetas['admin/roles/create'],
	'admin/roles/delete': adminRolesMetas['admin/roles/delete'],
	'admin/roles/list': adminRolesMetas['admin/roles/list'],
	'admin/roles/show': adminRolesMetas['admin/roles/show'],
	'admin/roles/unassign': adminRolesMetas['admin/roles/unassign'],
	'admin/roles/update': adminRolesMetas['admin/roles/update'],
	'admin/roles/update-default-policies': adminRolesMetas['admin/roles/update-default-policies'],
	'admin/roles/users': adminRolesMetas['admin/roles/users'],
	'admin/send-email': adminMetas['admin/send-email'],
	'admin/server-info': adminMetas['admin/server-info'],
	'admin/show-moderation-logs': adminMetas['admin/show-moderation-logs'],
	'admin/show-user': adminMetas['admin/show-user'],
	'admin/show-users': adminMetas['admin/show-users'],
	'admin/suspend-user': adminMetas['admin/suspend-user'],
	'admin/system-webhook/create': adminSystemWebhookMetas['admin/system-webhook/create'],
	'admin/system-webhook/delete': adminSystemWebhookMetas['admin/system-webhook/delete'],
	'admin/system-webhook/list': adminSystemWebhookMetas['admin/system-webhook/list'],
	'admin/system-webhook/show': adminSystemWebhookMetas['admin/system-webhook/show'],
	'admin/system-webhook/test': adminSystemWebhookMetas['admin/system-webhook/test'],
	'admin/system-webhook/update': adminSystemWebhookMetas['admin/system-webhook/update'],
	'admin/unset-mfa': adminMetas['admin/unset-mfa'],
	'admin/unset-user-avatar': adminMetas['admin/unset-user-avatar'],
	'admin/unset-user-banner': adminMetas['admin/unset-user-banner'],
	'admin/unsuspend-user': adminMetas['admin/unsuspend-user'],
	'admin/update-abuse-user-report': adminMetas['admin/update-abuse-user-report'],
	'admin/update-meta': adminMetas['admin/update-meta'],
	'admin/update-proxy-account': adminMetas['admin/update-proxy-account'],
	'admin/update-user-note': adminMetas['admin/update-user-note'],
	'announcements': miscMetas['announcements'],
	'announcements/show': miscMetas['announcements/show'],
	'antennas/create': antennasMetas['antennas/create'],
	'antennas/delete': antennasMetas['antennas/delete'],
	'antennas/list': antennasMetas['antennas/list'],
	'antennas/notes': antennasMetas['antennas/notes'],
	'antennas/remove-note': antennasMetas['antennas/remove-note'],
	'antennas/show': antennasMetas['antennas/show'],
	'antennas/update': antennasMetas['antennas/update'],
	'ap/get': miscMetas['ap/get'],
	'ap/show': miscMetas['ap/show'],
	'app/create': miscMetas['app/create'],
	'app/show': miscMetas['app/show'],
	'auth/accept': miscMetas['auth/accept'],
	'auth/session/generate': miscMetas['auth/session/generate'],
	'auth/session/show': miscMetas['auth/session/show'],
	'auth/session/userkey': miscMetas['auth/session/userkey'],
	'blocking/create': miscMetas['blocking/create'],
	'blocking/delete': miscMetas['blocking/delete'],
	'blocking/list': miscMetas['blocking/list'],
	'channels/create': channelsMetas['channels/create'],
	'channels/favorite': channelsMetas['channels/favorite'],
	'channels/featured': channelsMetas['channels/featured'],
	'channels/follow': channelsMetas['channels/follow'],
	'channels/followed': channelsMetas['channels/followed'],
	'channels/mute/create': channelsMetas['channels/mute/create'],
	'channels/mute/delete': channelsMetas['channels/mute/delete'],
	'channels/mute/list': channelsMetas['channels/mute/list'],
	'channels/my-favorites': channelsMetas['channels/my-favorites'],
	'channels/owned': channelsMetas['channels/owned'],
	'channels/search': channelsMetas['channels/search'],
	'channels/show': channelsMetas['channels/show'],
	'channels/timeline': channelsMetas['channels/timeline'],
	'channels/unfavorite': channelsMetas['channels/unfavorite'],
	'channels/unfollow': channelsMetas['channels/unfollow'],
	'channels/update': channelsMetas['channels/update'],
	'charts/active-users': chartsMetas['charts/active-users'],
	'charts/ap-request': chartsMetas['charts/ap-request'],
	'charts/drive': chartsMetas['charts/drive'],
	'charts/federation': chartsMetas['charts/federation'],
	'charts/instance': chartsMetas['charts/instance'],
	'charts/notes': chartsMetas['charts/notes'],
	'charts/user/drive': chartsMetas['charts/user/drive'],
	'charts/user/following': chartsMetas['charts/user/following'],
	'charts/user/notes': chartsMetas['charts/user/notes'],
	'charts/user/pv': chartsMetas['charts/user/pv'],
	'charts/user/reactions': chartsMetas['charts/user/reactions'],
	'charts/users': chartsMetas['charts/users'],
	'chat/history': chatMetas['chat/history'],
	'chat/messages/create-to-room': chatMetas['chat/messages/create-to-room'],
	'chat/messages/create-to-user': chatMetas['chat/messages/create-to-user'],
	'chat/messages/delete': chatMetas['chat/messages/delete'],
	'chat/messages/react': chatMetas['chat/messages/react'],
	'chat/messages/room-timeline': chatMetas['chat/messages/room-timeline'],
	'chat/messages/search': chatMetas['chat/messages/search'],
	'chat/messages/show': chatMetas['chat/messages/show'],
	'chat/messages/unreact': chatMetas['chat/messages/unreact'],
	'chat/messages/user-timeline': chatMetas['chat/messages/user-timeline'],
	'chat/read-all': chatMetas['chat/read-all'],
	'chat/rooms/create': chatMetas['chat/rooms/create'],
	'chat/rooms/delete': chatMetas['chat/rooms/delete'],
	'chat/rooms/invitations/create': chatMetas['chat/rooms/invitations/create'],
	'chat/rooms/invitations/ignore': chatMetas['chat/rooms/invitations/ignore'],
	'chat/rooms/invitations/inbox': chatMetas['chat/rooms/invitations/inbox'],
	'chat/rooms/invitations/outbox': chatMetas['chat/rooms/invitations/outbox'],
	'chat/rooms/join': chatMetas['chat/rooms/join'],
	'chat/rooms/joining': chatMetas['chat/rooms/joining'],
	'chat/rooms/leave': chatMetas['chat/rooms/leave'],
	'chat/rooms/members': chatMetas['chat/rooms/members'],
	'chat/rooms/mute': chatMetas['chat/rooms/mute'],
	'chat/rooms/owned': chatMetas['chat/rooms/owned'],
	'chat/rooms/show': chatMetas['chat/rooms/show'],
	'chat/rooms/update': chatMetas['chat/rooms/update'],
	'clips/add-note': clipsMetas['clips/add-note'],
	'clips/create': clipsMetas['clips/create'],
	'clips/delete': clipsMetas['clips/delete'],
	'clips/favorite': clipsMetas['clips/favorite'],
	'clips/list': clipsMetas['clips/list'],
	'clips/my-favorites': clipsMetas['clips/my-favorites'],
	'clips/notes': clipsMetas['clips/notes'],
	'clips/remove-note': clipsMetas['clips/remove-note'],
	'clips/show': clipsMetas['clips/show'],
	'clips/unfavorite': clipsMetas['clips/unfavorite'],
	'clips/update': clipsMetas['clips/update'],
	'drive': driveMetas['drive'],
	'drive/files': driveMetas['drive/files'],
	'drive/files/attached-chat-messages': driveMetas['drive/files/attached-chat-messages'],
	'drive/files/attached-notes': driveMetas['drive/files/attached-notes'],
	'drive/files/check-existence': driveMetas['drive/files/check-existence'],
	'drive/files/create': driveMetas['drive/files/create'],
	'drive/files/delete': driveMetas['drive/files/delete'],
	'drive/files/find': driveMetas['drive/files/find'],
	'drive/files/find-by-hash': driveMetas['drive/files/find-by-hash'],
	'drive/files/move-bulk': driveMetas['drive/files/move-bulk'],
	'drive/files/show': driveMetas['drive/files/show'],
	'drive/files/update': driveMetas['drive/files/update'],
	'drive/files/upload-from-url': driveMetas['drive/files/upload-from-url'],
	'drive/folders': driveMetas['drive/folders'],
	'drive/folders/create': driveMetas['drive/folders/create'],
	'drive/folders/delete': driveMetas['drive/folders/delete'],
	'drive/folders/find': driveMetas['drive/folders/find'],
	'drive/folders/show': driveMetas['drive/folders/show'],
	'drive/folders/update': driveMetas['drive/folders/update'],
	'drive/stream': driveMetas['drive/stream'],
	'email-address/available': miscMetas['email-address/available'],
	'emoji': miscMetas['emoji'],
	'emojis': miscMetas['emojis'],
	'endpoint': miscMetas['endpoint'],
	'endpoints': miscMetas['endpoints'],
	'export-custom-emojis': miscMetas['export-custom-emojis'],
	'federation/followers': federationMetas['federation/followers'],
	'federation/following': federationMetas['federation/following'],
	'federation/instances': federationMetas['federation/instances'],
	'federation/show-instance': federationMetas['federation/show-instance'],
	'federation/stats': federationMetas['federation/stats'],
	'federation/update-remote-user': federationMetas['federation/update-remote-user'],
	'federation/users': federationMetas['federation/users'],
	'fetch-external-resources': miscMetas['fetch-external-resources'],
	'fetch-rss': miscMetas['fetch-rss'],
	'flash/create': flashMetas['flash/create'],
	'flash/delete': flashMetas['flash/delete'],
	'flash/featured': flashMetas['flash/featured'],
	'flash/like': flashMetas['flash/like'],
	'flash/my': flashMetas['flash/my'],
	'flash/my-likes': flashMetas['flash/my-likes'],
	'flash/search': flashMetas['flash/search'],
	'flash/show': flashMetas['flash/show'],
	'flash/unlike': flashMetas['flash/unlike'],
	'flash/update': flashMetas['flash/update'],
	'following/create': followingMetas['following/create'],
	'following/delete': followingMetas['following/delete'],
	'following/invalidate': followingMetas['following/invalidate'],
	'following/list': followingMetas['following/list'],
	'following/requests/accept': followingMetas['following/requests/accept'],
	'following/requests/cancel': followingMetas['following/requests/cancel'],
	'following/requests/list': followingMetas['following/requests/list'],
	'following/requests/reject': followingMetas['following/requests/reject'],
	'following/requests/sent': followingMetas['following/requests/sent'],
	'following/update': followingMetas['following/update'],
	'following/update-all': followingMetas['following/update-all'],
	'gallery/featured': galleryMetas['gallery/featured'],
	'gallery/popular': galleryMetas['gallery/popular'],
	'gallery/posts': galleryMetas['gallery/posts'],
	'gallery/posts/create': galleryMetas['gallery/posts/create'],
	'gallery/posts/delete': galleryMetas['gallery/posts/delete'],
	'gallery/posts/like': galleryMetas['gallery/posts/like'],
	'gallery/posts/show': galleryMetas['gallery/posts/show'],
	'gallery/posts/unlike': galleryMetas['gallery/posts/unlike'],
	'gallery/posts/update': galleryMetas['gallery/posts/update'],
	'get-avatar-decorations': miscMetas['get-avatar-decorations'],
	'get-online-users-count': miscMetas['get-online-users-count'],
	'hashtags/list': hashtagsMetas['hashtags/list'],
	'hashtags/search': hashtagsMetas['hashtags/search'],
	'hashtags/show': hashtagsMetas['hashtags/show'],
	'hashtags/trend': hashtagsMetas['hashtags/trend'],
	'hashtags/users': hashtagsMetas['hashtags/users'],
	'i': iMetas['i'],
	'i/2fa/done': iMetas['i/2fa/done'],
	'i/2fa/key-done': iMetas['i/2fa/key-done'],
	'i/2fa/password-less': iMetas['i/2fa/password-less'],
	'i/2fa/register': iMetas['i/2fa/register'],
	'i/2fa/register-key': iMetas['i/2fa/register-key'],
	'i/2fa/remove-key': iMetas['i/2fa/remove-key'],
	'i/2fa/unregister': iMetas['i/2fa/unregister'],
	'i/2fa/update-key': iMetas['i/2fa/update-key'],
	'i/apps': iMetas['i/apps'],
	'i/authorized-apps': iMetas['i/authorized-apps'],
	'i/change-password': iMetas['i/change-password'],
	'i/claim-achievement': iMetas['i/claim-achievement'],
	'i/delete-account': iMetas['i/delete-account'],
	'i/export-antennas': iMetas['i/export-antennas'],
	'i/export-blocking': iMetas['i/export-blocking'],
	'i/export-clips': iMetas['i/export-clips'],
	'i/export-favorites': iMetas['i/export-favorites'],
	'i/export-following': iMetas['i/export-following'],
	'i/export-mute': iMetas['i/export-mute'],
	'i/export-notes': iMetas['i/export-notes'],
	'i/export-user-lists': iMetas['i/export-user-lists'],
	'i/favorites': iMetas['i/favorites'],
	'i/gallery/likes': iMetas['i/gallery/likes'],
	'i/gallery/posts': iMetas['i/gallery/posts'],
	'i/import-antennas': iMetas['i/import-antennas'],
	'i/import-blocking': iMetas['i/import-blocking'],
	'i/import-following': iMetas['i/import-following'],
	'i/import-muting': iMetas['i/import-muting'],
	'i/import-user-lists': iMetas['i/import-user-lists'],
	'i/move': iMetas['i/move'],
	'i/notifications': iMetas['i/notifications'],
	'i/notifications-grouped': iMetas['i/notifications-grouped'],
	'i/page-likes': iMetas['i/page-likes'],
	'i/pages': iMetas['i/pages'],
	'i/pin': iMetas['i/pin'],
	'i/read-announcement': iMetas['i/read-announcement'],
	'i/regenerate-token': iMetas['i/regenerate-token'],
	'i/registry/get': iMetas['i/registry/get'],
	'i/registry/get-all': iMetas['i/registry/get-all'],
	'i/registry/get-detail': iMetas['i/registry/get-detail'],
	'i/registry/keys': iMetas['i/registry/keys'],
	'i/registry/keys-with-type': iMetas['i/registry/keys-with-type'],
	'i/registry/remove': iMetas['i/registry/remove'],
	'i/registry/scopes-with-domain': iMetas['i/registry/scopes-with-domain'],
	'i/registry/set': iMetas['i/registry/set'],
	'i/revoke-token': iMetas['i/revoke-token'],
	'i/signin-history': iMetas['i/signin-history'],
	'i/unpin': iMetas['i/unpin'],
	'i/update': iMetas['i/update'],
	'i/update-email': iMetas['i/update-email'],
	'i/webhooks/create': iMetas['i/webhooks/create'],
	'i/webhooks/delete': iMetas['i/webhooks/delete'],
	'i/webhooks/list': iMetas['i/webhooks/list'],
	'i/webhooks/show': iMetas['i/webhooks/show'],
	'i/webhooks/test': iMetas['i/webhooks/test'],
	'i/webhooks/update': iMetas['i/webhooks/update'],
	'invite/create': miscMetas['invite/create'],
	'invite/delete': miscMetas['invite/delete'],
	'invite/limit': miscMetas['invite/limit'],
	'invite/list': miscMetas['invite/list'],
	'meta': miscMetas['meta'],
	'miauth/gen-token': miscMetas['miauth/gen-token'],
	'mute/create': miscMetas['mute/create'],
	'mute/delete': miscMetas['mute/delete'],
	'mute/list': miscMetas['mute/list'],
	'my/apps': miscMetas['my/apps'],
	'notes': notesMetas['notes'],
	'notes/children': notesMetas['notes/children'],
	'notes/clips': notesMetas['notes/clips'],
	'notes/conversation': notesMetas['notes/conversation'],
	'notes/create': notesMetas['notes/create'],
	'notes/delete': notesMetas['notes/delete'],
	'notes/drafts/count': notesMetas['notes/drafts/count'],
	'notes/drafts/create': notesMetas['notes/drafts/create'],
	'notes/drafts/delete': notesMetas['notes/drafts/delete'],
	'notes/drafts/list': notesMetas['notes/drafts/list'],
	'notes/drafts/update': notesMetas['notes/drafts/update'],
	'notes/favorites/create': notesMetas['notes/favorites/create'],
	'notes/favorites/delete': notesMetas['notes/favorites/delete'],
	'notes/featured': notesMetas['notes/featured'],
	'notes/global-timeline': notesMetas['notes/global-timeline'],
	'notes/hybrid-timeline': notesMetas['notes/hybrid-timeline'],
	'notes/local-timeline': notesMetas['notes/local-timeline'],
	'notes/mentions': notesMetas['notes/mentions'],
	'notes/polls/recommendation': notesMetas['notes/polls/recommendation'],
	'notes/polls/vote': notesMetas['notes/polls/vote'],
	'notes/reactions': notesMetas['notes/reactions'],
	'notes/reactions/create': notesMetas['notes/reactions/create'],
	'notes/reactions/delete': notesMetas['notes/reactions/delete'],
	'notes/renotes': notesMetas['notes/renotes'],
	'notes/replies': notesMetas['notes/replies'],
	'notes/search': notesMetas['notes/search'],
	'notes/search-by-tag': notesMetas['notes/search-by-tag'],
	'notes/show': notesMetas['notes/show'],
	'notes/show-partial-bulk': notesMetas['notes/show-partial-bulk'],
	'notes/state': notesMetas['notes/state'],
	'notes/thread-muting/create': notesMetas['notes/thread-muting/create'],
	'notes/thread-muting/delete': notesMetas['notes/thread-muting/delete'],
	'notes/timeline': notesMetas['notes/timeline'],
	'notes/translate': notesMetas['notes/translate'],
	'notes/unrenote': notesMetas['notes/unrenote'],
	'notes/user-list-timeline': notesMetas['notes/user-list-timeline'],
	'notifications/create': miscMetas['notifications/create'],
	'notifications/delete': miscMetas['notifications/delete'],
	'notifications/flush': miscMetas['notifications/flush'],
	'notifications/mark-all-as-read': miscMetas['notifications/mark-all-as-read'],
	'notifications/test-notification': miscMetas['notifications/test-notification'],
	'page-push': miscMetas['page-push'],
	'pages/create': pagesMetas['pages/create'],
	'pages/delete': pagesMetas['pages/delete'],
	'pages/featured': pagesMetas['pages/featured'],
	'pages/like': pagesMetas['pages/like'],
	'pages/show': pagesMetas['pages/show'],
	'pages/unlike': pagesMetas['pages/unlike'],
	'pages/update': pagesMetas['pages/update'],
	'ping': miscMetas['ping'],
	'pinned-users': miscMetas['pinned-users'],
	'promo/read': miscMetas['promo/read'],
	'renote-mute/create': miscMetas['renote-mute/create'],
	'renote-mute/delete': miscMetas['renote-mute/delete'],
	'renote-mute/list': miscMetas['renote-mute/list'],
	'request-reset-password': miscMetas['request-reset-password'],
	'reset-db': miscMetas['reset-db'],
	'reset-password': miscMetas['reset-password'],
	'retention': miscMetas['retention'],
	'roles/list': miscMetas['roles/list'],
	'roles/notes': miscMetas['roles/notes'],
	'roles/show': miscMetas['roles/show'],
	'roles/users': miscMetas['roles/users'],
	'server-info': miscMetas['server-info'],
	'stats': miscMetas['stats'],
	'sw/register': miscMetas['sw/register'],
	'sw/show-registration': miscMetas['sw/show-registration'],
	'sw/unregister': miscMetas['sw/unregister'],
	'sw/update-registration': miscMetas['sw/update-registration'],
	'test': miscMetas['test'],
	'username/available': miscMetas['username/available'],
	'users': usersMetas['users'],
	'users/achievements': usersMetas['users/achievements'],
	'users/clips': usersMetas['users/clips'],
	'users/featured-notes': usersMetas['users/featured-notes'],
	'users/flashs': usersMetas['users/flashs'],
	'users/followers': usersMetas['users/followers'],
	'users/following': usersMetas['users/following'],
	'users/gallery/posts': usersMetas['users/gallery/posts'],
	'users/get-following-users-by-birthday': usersMetas['users/get-following-users-by-birthday'],
	'users/get-frequently-replied-users': usersMetas['users/get-frequently-replied-users'],
	'users/lists/create': usersMetas['users/lists/create'],
	'users/lists/create-from-public': usersMetas['users/lists/create-from-public'],
	'users/lists/delete': usersMetas['users/lists/delete'],
	'users/lists/favorite': usersMetas['users/lists/favorite'],
	'users/lists/get-memberships': usersMetas['users/lists/get-memberships'],
	'users/lists/list': usersMetas['users/lists/list'],
	'users/lists/pull': usersMetas['users/lists/pull'],
	'users/lists/push': usersMetas['users/lists/push'],
	'users/lists/show': usersMetas['users/lists/show'],
	'users/lists/unfavorite': usersMetas['users/lists/unfavorite'],
	'users/lists/update': usersMetas['users/lists/update'],
	'users/lists/update-membership': usersMetas['users/lists/update-membership'],
	'users/notes': usersMetas['users/notes'],
	'users/pages': usersMetas['users/pages'],
	'users/reactions': usersMetas['users/reactions'],
	'users/recommendation': usersMetas['users/recommendation'],
	'users/relation': usersMetas['users/relation'],
	'users/report-abuse': usersMetas['users/report-abuse'],
	'users/search': usersMetas['users/search'],
	'users/search-by-username-and-host': usersMetas['users/search-by-username-and-host'],
	'users/show': usersMetas['users/show'],
	'users/update-memo': usersMetas['users/update-memo'],
	'v2/admin/emoji/list': miscMetas['v2/admin/emoji/list'],
	'verify-email': miscMetas['verify-email'],
};

const groupedEndpointNames = endpointMetaGroups.flatMap(group => Object.keys(group));
const duplicateEndpointNames = groupedEndpointNames.filter((name, index) => groupedEndpointNames.indexOf(name) !== index);
if (duplicateEndpointNames.length > 0) {
	throw new Error(`Duplicate endpoint metadata: ${[...new Set(duplicateEndpointNames)].join(', ')}`);
}

const consolidatedEndpointNames = Object.keys(endpointMetas);
const omittedEndpointNames = groupedEndpointNames.filter(name => !Object.hasOwn(endpointMetas, name));
const unknownEndpointNames = consolidatedEndpointNames.filter(name => !groupedEndpointNames.includes(name));
if (omittedEndpointNames.length > 0 || unknownEndpointNames.length > 0) {
	throw new Error([
		omittedEndpointNames.length > 0 ? `Endpoint metadata omitted from the consolidated map: ${omittedEndpointNames.join(', ')}` : '',
		unknownEndpointNames.length > 0 ? `Unknown endpoint metadata in the consolidated map: ${unknownEndpointNames.join(', ')}` : '',
	].filter(Boolean).join('\n'));
}
