# このconfigは、dockerでMisskey本体を起動せず、ValkeyとPostgreSQLなどだけを起動します

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'

services:
  valkey:
    restart: unless-stopped
    image: valkey/valkey:8-alpine
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ../redis:/data
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 3s
      start_period: 5s
      retries: 20
    stop_grace_period: 30s
    logging: *default-logging

  db:
    restart: unless-stopped
    image: postgres:18-alpine
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - ../.config/docker.env
    volumes:
      - ../db:/var/lib/postgresql
    shm_size: 256mb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 20
    stop_grace_period: 60s
    logging: *default-logging

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - ../.config/meilisearch.env
#    volumes:
#      - ../meili_data:/meili_data
