/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const DI = {
	config: Symbol('config'),
	db: Symbol('db'),
	drizzle: Symbol('drizzle'),
	drizzlePool: Symbol('drizzlePool'),
	meta: Symbol('meta'),
	meilisearch: Symbol('meilisearch'),
	redis: Symbol('redis'),
	redisForPub: Symbol('redisForPub'),
	redisForSub: Symbol('redisForSub'),
	redisForTimelines: Symbol('redisForTimelines'),
	redisForReactions: Symbol('redisForReactions'),

	//#region Repositories
	usersRepository: Symbol('usersRepository'),
	notesRepository: Symbol('notesRepository'),
	announcementsRepository: Symbol('announcementsRepository'),
	announcementReadsRepository: Symbol('announcementReadsRepository'),
	appsRepository: Symbol('appsRepository'),
	noteFavoritesRepository: Symbol('noteFavoritesRepository'),
	noteThreadMutingsRepository: Symbol('noteThreadMutingsRepository'),
	noteReactionsRepository: Symbol('noteReactionsRepository'),
	pollsRepository: Symbol('pollsRepository'),
	pollVotesRepository: Symbol('pollVotesRepository'),
	userProfilesRepository: Symbol('userProfilesRepository'),
	userSecurityKeysRepository: Symbol('userSecurityKeysRepository'),
	userListsRepository: Symbol('userListsRepository'),
	userListMembershipsRepository: Symbol('userListMembershipsRepository'),
	userNotePiningsRepository: Symbol('userNotePiningsRepository'),
	followingsRepository: Symbol('followingsRepository'),
	followRequestsRepository: Symbol('followRequestsRepository'),
	instancesRepository: Symbol('instancesRepository'),
	emojisRepository: Symbol('emojisRepository'),
	driveFilesRepository: Symbol('driveFilesRepository'),
	driveFoldersRepository: Symbol('driveFoldersRepository'),
	mutingsRepository: Symbol('mutingsRepository'),
	renoteMutingsRepository: Symbol('renoteMutingsRepository'),
	blockingsRepository: Symbol('blockingsRepository'),
	hashtagsRepository: Symbol('hashtagsRepository'),
	abuseUserReportsRepository: Symbol('abuseUserReportsRepository'),
	abuseReportNotificationRecipientRepository: Symbol('abuseReportNotificationRecipientRepository'),
	registrationTicketsRepository: Symbol('registrationTicketsRepository'),
	authSessionsRepository: Symbol('authSessionsRepository'),
	accessTokensRepository: Symbol('accessTokensRepository'),
	pagesRepository: Symbol('pagesRepository'),
	pageLikesRepository: Symbol('pageLikesRepository'),
	galleryPostsRepository: Symbol('galleryPostsRepository'),
	galleryLikesRepository: Symbol('galleryLikesRepository'),
	clipsRepository: Symbol('clipsRepository'),
	clipNotesRepository: Symbol('clipNotesRepository'),
	clipFavoritesRepository: Symbol('clipFavoritesRepository'),
	antennasRepository: Symbol('antennasRepository'),
	channelsRepository: Symbol('channelsRepository'),
	channelFollowingsRepository: Symbol('channelFollowingsRepository'),
	channelFavoritesRepository: Symbol('channelFavoritesRepository'),
	channelMutingRepository: Symbol('channelMutingRepository'),
	webhooksRepository: Symbol('webhooksRepository'),
	systemWebhooksRepository: Symbol('systemWebhooksRepository'),
	adsRepository: Symbol('adsRepository'),
	rolesRepository: Symbol('rolesRepository'),
	roleAssignmentsRepository: Symbol('roleAssignmentsRepository'),
	flashsRepository: Symbol('flashsRepository'),
	flashLikesRepository: Symbol('flashLikesRepository'),
	chatMessagesRepository: Symbol('chatMessagesRepository'),
	chatRoomsRepository: Symbol('chatRoomsRepository'),
	chatRoomMembershipsRepository: Symbol('chatRoomMembershipsRepository'),
	chatRoomInvitationsRepository: Symbol('chatRoomInvitationsRepository'),
	noteDraftsRepository: Symbol('noteDraftsRepository'),
	//#endregion
};
