/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { sql } from 'drizzle-orm';
import { bigint, boolean, integer, jsonb, pgEnum, pgTable, varchar } from 'drizzle-orm/pg-core';
import type { SoftwareSuspension } from '@/models/Meta.js';

type ClientOptions = {
	entrancePageStyle: 'classic' | 'simple';
	showTimelineForVisitor: boolean;
	showActivitiesForVisitor: boolean;
};

const emptyVarcharArray = sql`'{}'::character varying[]`;

export const metaSensitiveMediaDetectionEnum = pgEnum('meta_sensitivemediadetection_enum', ['none', 'all', 'local', 'remote']);
export const metaSensitiveMediaDetectionSensitivityEnum = pgEnum('meta_sensitivemediadetectionsensitivity_enum', ['medium', 'low', 'high', 'veryLow', 'veryHigh']);

export const meta = pgTable('meta', {
	id: varchar({ length: 32 }).primaryKey().notNull(),
	rootUserId: varchar({ length: 32 }),
	name: varchar({ length: 1024 }),
	shortName: varchar({ length: 64 }),
	description: varchar({ length: 1024 }),
	maintainerName: varchar({ length: 1024 }),
	maintainerEmail: varchar({ length: 1024 }),
	disableRegistration: boolean().default(true).notNull(),
	langs: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	pinnedUsers: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	hiddenTags: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	blockedHosts: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	sensitiveWords: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	prohibitedWords: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	prohibitedWordsForNameOfUser: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	silencedHosts: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	mediaSilencedHosts: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	themeColor: varchar({ length: 1024 }),
	mascotImageUrl: varchar({ length: 1024 }),
	bannerUrl: varchar({ length: 1024 }),
	backgroundImageUrl: varchar({ length: 1024 }),
	logoImageUrl: varchar({ length: 1024 }),
	iconUrl: varchar({ length: 1024 }),
	app192IconUrl: varchar({ length: 1024 }),
	app512IconUrl: varchar({ length: 1024 }),
	serverErrorImageUrl: varchar({ length: 1024 }),
	notFoundImageUrl: varchar({ length: 1024 }),
	infoImageUrl: varchar({ length: 1024 }),
	cacheRemoteFiles: boolean().default(false).notNull(),
	cacheRemoteSensitiveFiles: boolean().default(true).notNull(),
	emailRequiredForSignup: boolean().default(false).notNull(),
	enableHcaptcha: boolean().default(false).notNull(),
	hcaptchaSiteKey: varchar({ length: 1024 }),
	hcaptchaSecretKey: varchar({ length: 1024 }),
	enableMcaptcha: boolean().default(false).notNull(),
	mcaptchaSitekey: varchar({ length: 1024 }),
	mcaptchaSecretKey: varchar({ length: 1024 }),
	mcaptchaInstanceUrl: varchar({ length: 1024 }),
	enableRecaptcha: boolean().default(false).notNull(),
	recaptchaSiteKey: varchar({ length: 1024 }),
	recaptchaSecretKey: varchar({ length: 1024 }),
	enableTurnstile: boolean().default(false).notNull(),
	turnstileSiteKey: varchar({ length: 1024 }),
	turnstileSecretKey: varchar({ length: 1024 }),
	enableTestcaptcha: boolean().default(false).notNull(),
	sensitiveMediaDetection: metaSensitiveMediaDetectionEnum().default('none').notNull(),
	sensitiveMediaDetectionSensitivity: metaSensitiveMediaDetectionSensitivityEnum().default('medium').notNull(),
	setSensitiveFlagAutomatically: boolean().default(false).notNull(),
	enableSensitiveMediaDetectionForVideos: boolean().default(false).notNull(),
	sensitiveMediaDetectionApiUrl: varchar({ length: 1024 }),
	sensitiveMediaDetectionApiKey: varchar({ length: 1024 }),
	sensitiveMediaDetectionTimeout: integer().default(60000).notNull(),
	sensitiveMediaDetectionMaxImagesPerRequest: integer().default(4).notNull(),
	enableEmail: boolean().default(false).notNull(),
	email: varchar({ length: 1024 }),
	smtpSecure: boolean().default(false).notNull(),
	smtpHost: varchar({ length: 1024 }),
	smtpPort: integer(),
	smtpUser: varchar({ length: 1024 }),
	smtpPass: varchar({ length: 1024 }),
	enableServiceWorker: boolean().default(false).notNull(),
	swPublicKey: varchar({ length: 1024 }),
	swPrivateKey: varchar({ length: 1024 }),
	deeplAuthKey: varchar({ length: 1024 }),
	deeplIsPro: boolean().default(false).notNull(),
	termsOfServiceUrl: varchar({ length: 1024 }),
	repositoryUrl: varchar({ length: 1024 }).default('https://github.com/misskey-dev/misskey'),
	feedbackUrl: varchar({ length: 1024 }).default('https://github.com/misskey-dev/misskey/issues/new'),
	impressumUrl: varchar({ length: 1024 }),
	privacyPolicyUrl: varchar({ length: 1024 }),
	inquiryUrl: varchar({ length: 1024 }),
	defaultLightTheme: varchar({ length: 8192 }),
	defaultDarkTheme: varchar({ length: 8192 }),
	useObjectStorage: boolean().default(false).notNull(),
	objectStorageBucket: varchar({ length: 1024 }),
	objectStoragePrefix: varchar({ length: 1024 }),
	objectStorageBaseUrl: varchar({ length: 1024 }),
	objectStorageEndpoint: varchar({ length: 1024 }),
	objectStorageRegion: varchar({ length: 1024 }),
	objectStorageAccessKey: varchar({ length: 1024 }),
	objectStorageSecretKey: varchar({ length: 1024 }),
	objectStoragePort: integer(),
	objectStorageUseSSL: boolean().default(true).notNull(),
	objectStorageUseProxy: boolean().default(true).notNull(),
	objectStorageSetPublicRead: boolean().default(false).notNull(),
	objectStorageS3ForcePathStyle: boolean().default(true).notNull(),
	enableIpLogging: boolean().default(false).notNull(),
	enableActiveEmailValidation: boolean().default(true).notNull(),
	enableVerifymailApi: boolean().default(false).notNull(),
	verifymailAuthKey: varchar({ length: 1024 }),
	enableTruemailApi: boolean().default(false).notNull(),
	truemailInstance: varchar({ length: 1024 }),
	truemailAuthKey: varchar({ length: 1024 }),
	enableChartsForRemoteUser: boolean().default(true).notNull(),
	enableChartsForFederatedInstances: boolean().default(true).notNull(),
	enableStatsForFederatedInstances: boolean().default(true).notNull(),
	enableServerMachineStats: boolean().default(false).notNull(),
	enableIdenticonGeneration: boolean().default(true).notNull(),
	policies: jsonb().$type<Record<string, any>>().default({}).notNull(),
	serverRules: varchar({ length: 280 }).array().default(emptyVarcharArray).notNull(),
	manifestJsonOverride: varchar({ length: 8192 }).default('{}').notNull(),
	bannedEmailDomains: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	preservedUsernames: varchar({ length: 1024 }).array().default([
		'admin',
		'administrator',
		'root',
		'system',
		'maintainer',
		'host',
		'mod',
		'moderator',
		'owner',
		'superuser',
		'staff',
		'auth',
		'i',
		'me',
		'everyone',
		'all',
		'mention',
		'mentions',
		'example',
		'user',
		'users',
		'account',
		'accounts',
		'official',
		'help',
		'helps',
		'support',
		'supports',
		'info',
		'information',
		'informations',
		'announce',
		'announces',
		'announcement',
		'announcements',
		'notice',
		'notification',
		'notifications',
		'dev',
		'developer',
		'developers',
		'tech',
		'misskey',
	]).notNull(),
	enableFanoutTimeline: boolean().default(true).notNull(),
	enableFanoutTimelineDbFallback: boolean().default(true).notNull(),
	perLocalUserUserTimelineCacheMax: integer().default(300).notNull(),
	perRemoteUserUserTimelineCacheMax: integer().default(100).notNull(),
	perUserHomeTimelineCacheMax: integer().default(300).notNull(),
	perUserListTimelineCacheMax: integer().default(300).notNull(),
	enableReactionsBuffering: boolean().default(false).notNull(),
	notesPerOneAd: integer().default(0).notNull(),
	urlPreviewEnabled: boolean().default(true).notNull(),
	urlPreviewAllowRedirect: boolean().default(true).notNull(),
	urlPreviewTimeout: integer().default(10000).notNull(),
	urlPreviewMaximumContentLength: bigint({ mode: 'number' }).default(1024 * 1024 * 10).notNull(),
	urlPreviewRequireContentLength: boolean().default(false).notNull(),
	urlPreviewSummaryProxyUrl: varchar({ length: 1024 }),
	urlPreviewUserAgent: varchar({ length: 1024 }),
	federation: varchar({ length: 128, enum: ['all', 'specified', 'none'] }).default('none').notNull(),
	federationHosts: varchar({ length: 1024 }).array().default(emptyVarcharArray).notNull(),
	ugcVisibilityForVisitor: varchar({ length: 128, enum: ['all', 'local', 'none'] }).default('local').notNull(),
	googleAnalyticsMeasurementId: varchar({ length: 64 }),
	deliverSuspendedSoftware: jsonb().$type<SoftwareSuspension[]>().default([]).notNull(),
	singleUserMode: boolean().default(false).notNull(),
	proxyRemoteFiles: boolean().default(true).notNull(),
	signToActivityPubGet: boolean().default(true).notNull(),
	allowExternalApRedirect: boolean().default(true).notNull(),
	enableRemoteNotesCleaning: boolean().default(false).notNull(),
	remoteNotesCleaningMaxProcessingDurationInMinutes: integer().default(60).notNull(),
	remoteNotesCleaningExpiryDaysForEachNotes: integer().default(90).notNull(),
	showRoleBadgesOfRemoteUsers: boolean().default(false).notNull(),
	clientOptions: jsonb().$type<ClientOptions>().default({} as ClientOptions).notNull(),
});

export type MetaRow = typeof meta.$inferSelect;
export type MetaInsert = typeof meta.$inferInsert;
