-- チャート集計テーブル(hour/day足×12指標=24テーブル)。core/chart/core.ts のジェネリックなraw SQLクエリ実行専用で、
-- drizzle-ormのpgTable定義を持たないため drizzle-kit generate では検出できない。旧 0000000000001-InitialSchema.js から一言一句そのまま移植。
CREATE TABLE "__chart__federation" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "unique_temp___deliveredInstances" character varying array NOT NULL DEFAULT '{}', "___deliveredInstances" smallint NOT NULL DEFAULT '0', "unique_temp___inboxInstances" character varying array NOT NULL DEFAULT '{}', "___inboxInstances" smallint NOT NULL DEFAULT '0', "unique_temp___stalled" character varying array NOT NULL DEFAULT '{}', "___stalled" smallint NOT NULL DEFAULT '0', "___sub" smallint NOT NULL DEFAULT '0', "___pub" smallint NOT NULL DEFAULT '0', "___pubsub" smallint NOT NULL DEFAULT '0', "___subActive" smallint NOT NULL DEFAULT '0', "___pubActive" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_36cb699c49580d4e6c2e6159f97" UNIQUE ("date"), CONSTRAINT "PK_b39dcd31a0fe1a7757e348e85fd" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_36cb699c49580d4e6c2e6159f9" ON "__chart__federation"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__federation" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "unique_temp___deliveredInstances" character varying array NOT NULL DEFAULT '{}', "___deliveredInstances" smallint NOT NULL DEFAULT '0', "unique_temp___inboxInstances" character varying array NOT NULL DEFAULT '{}', "___inboxInstances" smallint NOT NULL DEFAULT '0', "unique_temp___stalled" character varying array NOT NULL DEFAULT '{}', "___stalled" smallint NOT NULL DEFAULT '0', "___sub" smallint NOT NULL DEFAULT '0', "___pub" smallint NOT NULL DEFAULT '0', "___pubsub" smallint NOT NULL DEFAULT '0', "___subActive" smallint NOT NULL DEFAULT '0', "___pubActive" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_617a8fe225a6e701d89e02d2c74" UNIQUE ("date"), CONSTRAINT "PK_7ca721c769f31698e0e1331e8e6" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_617a8fe225a6e701d89e02d2c7" ON "__chart_day__federation"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart__notes" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_total" integer NOT NULL DEFAULT '0', "___local_inc" integer NOT NULL DEFAULT '0', "___local_dec" integer NOT NULL DEFAULT '0', "___local_diffs_normal" integer NOT NULL DEFAULT '0', "___local_diffs_reply" integer NOT NULL DEFAULT '0', "___local_diffs_renote" integer NOT NULL DEFAULT '0', "___local_diffs_withFile" integer NOT NULL DEFAULT '0', "___remote_total" integer NOT NULL DEFAULT '0', "___remote_inc" integer NOT NULL DEFAULT '0', "___remote_dec" integer NOT NULL DEFAULT '0', "___remote_diffs_normal" integer NOT NULL DEFAULT '0', "___remote_diffs_reply" integer NOT NULL DEFAULT '0', "___remote_diffs_renote" integer NOT NULL DEFAULT '0', "___remote_diffs_withFile" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_42eb716a37d381cdf566192b2be" UNIQUE ("date"), CONSTRAINT "PK_0aec823fa85c7f901bdb3863b14" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_42eb716a37d381cdf566192b2b" ON "__chart__notes"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__notes" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_total" integer NOT NULL DEFAULT '0', "___local_inc" integer NOT NULL DEFAULT '0', "___local_dec" integer NOT NULL DEFAULT '0', "___local_diffs_normal" integer NOT NULL DEFAULT '0', "___local_diffs_reply" integer NOT NULL DEFAULT '0', "___local_diffs_renote" integer NOT NULL DEFAULT '0', "___local_diffs_withFile" integer NOT NULL DEFAULT '0', "___remote_total" integer NOT NULL DEFAULT '0', "___remote_inc" integer NOT NULL DEFAULT '0', "___remote_dec" integer NOT NULL DEFAULT '0', "___remote_diffs_normal" integer NOT NULL DEFAULT '0', "___remote_diffs_reply" integer NOT NULL DEFAULT '0', "___remote_diffs_renote" integer NOT NULL DEFAULT '0', "___remote_diffs_withFile" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_1a527b423ad0858a1af5a056d43" UNIQUE ("date"), CONSTRAINT "PK_1fa4139e1f338272b758d05e090" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_1a527b423ad0858a1af5a056d4" ON "__chart_day__notes"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart__users" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_total" integer NOT NULL DEFAULT '0', "___local_inc" smallint NOT NULL DEFAULT '0', "___local_dec" smallint NOT NULL DEFAULT '0', "___remote_total" integer NOT NULL DEFAULT '0', "___remote_inc" smallint NOT NULL DEFAULT '0', "___remote_dec" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_845254b3eaf708ae8a6cac30265" UNIQUE ("date"), CONSTRAINT "PK_4dfcf2c78d03524b9eb2c99d328" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_845254b3eaf708ae8a6cac3026" ON "__chart__users"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__users" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_total" integer NOT NULL DEFAULT '0', "___local_inc" smallint NOT NULL DEFAULT '0', "___local_dec" smallint NOT NULL DEFAULT '0', "___remote_total" integer NOT NULL DEFAULT '0', "___remote_inc" smallint NOT NULL DEFAULT '0', "___remote_dec" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_cad6e07c20037f31cdba8a350c3" UNIQUE ("date"), CONSTRAINT "PK_d7f7185abb9851f70c4726c54bd" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_cad6e07c20037f31cdba8a350c" ON "__chart_day__users"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart__active_users" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___readWrite" integer NOT NULL DEFAULT '0', "unique_temp___read" character varying array NOT NULL DEFAULT '{}', "___read" integer NOT NULL DEFAULT '0', "unique_temp___write" character varying array NOT NULL DEFAULT '{}', "___write" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinWeek" character varying array NOT NULL DEFAULT '{}', "___registeredWithinWeek" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinMonth" character varying array NOT NULL DEFAULT '{}', "___registeredWithinMonth" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinYear" character varying array NOT NULL DEFAULT '{}', "___registeredWithinYear" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideWeek" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideWeek" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideMonth" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideMonth" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideYear" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideYear" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_0ad37b7ef50f4ddc84363d7ccca" UNIQUE ("date"), CONSTRAINT "PK_317237a9f733b970604a11e314f" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_0ad37b7ef50f4ddc84363d7ccc" ON "__chart__active_users"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__active_users" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___readWrite" integer NOT NULL DEFAULT '0', "unique_temp___read" character varying array NOT NULL DEFAULT '{}', "___read" integer NOT NULL DEFAULT '0', "unique_temp___write" character varying array NOT NULL DEFAULT '{}', "___write" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinWeek" character varying array NOT NULL DEFAULT '{}', "___registeredWithinWeek" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinMonth" character varying array NOT NULL DEFAULT '{}', "___registeredWithinMonth" integer NOT NULL DEFAULT '0', "unique_temp___registeredWithinYear" character varying array NOT NULL DEFAULT '{}', "___registeredWithinYear" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideWeek" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideWeek" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideMonth" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideMonth" integer NOT NULL DEFAULT '0', "unique_temp___registeredOutsideYear" character varying array NOT NULL DEFAULT '{}', "___registeredOutsideYear" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_d5954f3df5e5e3bdfc3c03f3906" UNIQUE ("date"), CONSTRAINT "PK_b1790489b14f005ae8f404f5795" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_d5954f3df5e5e3bdfc3c03f390" ON "__chart_day__active_users"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart__instance" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___requests_failed" smallint NOT NULL DEFAULT '0', "___requests_succeeded" smallint NOT NULL DEFAULT '0', "___requests_received" smallint NOT NULL DEFAULT '0', "___notes_total" integer NOT NULL DEFAULT '0', "___notes_inc" integer NOT NULL DEFAULT '0', "___notes_dec" integer NOT NULL DEFAULT '0', "___notes_diffs_normal" integer NOT NULL DEFAULT '0', "___notes_diffs_reply" integer NOT NULL DEFAULT '0', "___notes_diffs_renote" integer NOT NULL DEFAULT '0', "___notes_diffs_withFile" integer NOT NULL DEFAULT '0', "___users_total" integer NOT NULL DEFAULT '0', "___users_inc" smallint NOT NULL DEFAULT '0', "___users_dec" smallint NOT NULL DEFAULT '0', "___following_total" integer NOT NULL DEFAULT '0', "___following_inc" smallint NOT NULL DEFAULT '0', "___following_dec" smallint NOT NULL DEFAULT '0', "___followers_total" integer NOT NULL DEFAULT '0', "___followers_inc" smallint NOT NULL DEFAULT '0', "___followers_dec" smallint NOT NULL DEFAULT '0', "___drive_totalFiles" integer NOT NULL DEFAULT '0', "___drive_incFiles" integer NOT NULL DEFAULT '0', "___drive_decFiles" integer NOT NULL DEFAULT '0', "___drive_incUsage" integer NOT NULL DEFAULT '0', "___drive_decUsage" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_39ee857ab2f23493037c6b66311" UNIQUE ("date", "group"), CONSTRAINT "PK_1267c67c7c2d47b4903975f2c00" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_39ee857ab2f23493037c6b6631" ON "__chart__instance"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__instance" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___requests_failed" smallint NOT NULL DEFAULT '0', "___requests_succeeded" smallint NOT NULL DEFAULT '0', "___requests_received" smallint NOT NULL DEFAULT '0', "___notes_total" integer NOT NULL DEFAULT '0', "___notes_inc" integer NOT NULL DEFAULT '0', "___notes_dec" integer NOT NULL DEFAULT '0', "___notes_diffs_normal" integer NOT NULL DEFAULT '0', "___notes_diffs_reply" integer NOT NULL DEFAULT '0', "___notes_diffs_renote" integer NOT NULL DEFAULT '0', "___notes_diffs_withFile" integer NOT NULL DEFAULT '0', "___users_total" integer NOT NULL DEFAULT '0', "___users_inc" smallint NOT NULL DEFAULT '0', "___users_dec" smallint NOT NULL DEFAULT '0', "___following_total" integer NOT NULL DEFAULT '0', "___following_inc" smallint NOT NULL DEFAULT '0', "___following_dec" smallint NOT NULL DEFAULT '0', "___followers_total" integer NOT NULL DEFAULT '0', "___followers_inc" smallint NOT NULL DEFAULT '0', "___followers_dec" smallint NOT NULL DEFAULT '0', "___drive_totalFiles" integer NOT NULL DEFAULT '0', "___drive_incFiles" integer NOT NULL DEFAULT '0', "___drive_decFiles" integer NOT NULL DEFAULT '0', "___drive_incUsage" integer NOT NULL DEFAULT '0', "___drive_decUsage" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_fea7c0278325a1a2492f2d6acbf" UNIQUE ("date", "group"), CONSTRAINT "PK_479a8ff9d959274981087043023" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_fea7c0278325a1a2492f2d6acb" ON "__chart_day__instance"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__per_user_notes" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___total" integer NOT NULL DEFAULT '0', "___inc" smallint NOT NULL DEFAULT '0', "___dec" smallint NOT NULL DEFAULT '0', "___diffs_normal" smallint NOT NULL DEFAULT '0', "___diffs_reply" smallint NOT NULL DEFAULT '0', "___diffs_renote" smallint NOT NULL DEFAULT '0', "___diffs_withFile" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_5048e9daccbbbc6d567bb142d34" UNIQUE ("date", "group"), CONSTRAINT "PK_334acf6e915af2f29edc11b8e50" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_5048e9daccbbbc6d567bb142d3" ON "__chart__per_user_notes"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__per_user_notes" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___total" integer NOT NULL DEFAULT '0', "___inc" smallint NOT NULL DEFAULT '0', "___dec" smallint NOT NULL DEFAULT '0', "___diffs_normal" smallint NOT NULL DEFAULT '0', "___diffs_reply" smallint NOT NULL DEFAULT '0', "___diffs_renote" smallint NOT NULL DEFAULT '0', "___diffs_withFile" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_c5545d4b31cdc684034e33b81c3" UNIQUE ("date", "group"), CONSTRAINT "PK_58bab6b6d3ad9310cbc7460fd28" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_c5545d4b31cdc684034e33b81c" ON "__chart_day__per_user_notes"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__per_user_pv" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "unique_temp___upv_user" character varying array NOT NULL DEFAULT '{}', "___upv_user" smallint NOT NULL DEFAULT '0', "___pv_user" smallint NOT NULL DEFAULT '0', "unique_temp___upv_visitor" character varying array NOT NULL DEFAULT '{}', "___upv_visitor" smallint NOT NULL DEFAULT '0', "___pv_visitor" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_f2a56da57921ca8439f45c1d95f" UNIQUE ("date", "group"), CONSTRAINT "PK_3c938a24f0203b5bd13fab51059" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_f2a56da57921ca8439f45c1d95" ON "__chart__per_user_pv"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__per_user_pv" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "unique_temp___upv_user" character varying array NOT NULL DEFAULT '{}', "___upv_user" smallint NOT NULL DEFAULT '0', "___pv_user" smallint NOT NULL DEFAULT '0', "unique_temp___upv_visitor" character varying array NOT NULL DEFAULT '{}', "___upv_visitor" smallint NOT NULL DEFAULT '0', "___pv_visitor" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_f221e45cfac5bea0ce0f3149fbb" UNIQUE ("date", "group"), CONSTRAINT "PK_0085d7542f6772e99b9dcfb0a9c" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_f221e45cfac5bea0ce0f3149fb" ON "__chart_day__per_user_pv"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__drive" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_incCount" integer NOT NULL DEFAULT '0', "___local_incSize" integer NOT NULL DEFAULT '0', "___local_decCount" integer NOT NULL DEFAULT '0', "___local_decSize" integer NOT NULL DEFAULT '0', "___remote_incCount" integer NOT NULL DEFAULT '0', "___remote_incSize" integer NOT NULL DEFAULT '0', "___remote_decCount" integer NOT NULL DEFAULT '0', "___remote_decSize" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_13565815f618a1ff53886c5b28a" UNIQUE ("date"), CONSTRAINT "PK_f96bc548a765cd4b3b354221ce7" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_13565815f618a1ff53886c5b28" ON "__chart__drive"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__drive" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___local_incCount" integer NOT NULL DEFAULT '0', "___local_incSize" integer NOT NULL DEFAULT '0', "___local_decCount" integer NOT NULL DEFAULT '0', "___local_decSize" integer NOT NULL DEFAULT '0', "___remote_incCount" integer NOT NULL DEFAULT '0', "___remote_incSize" integer NOT NULL DEFAULT '0', "___remote_decCount" integer NOT NULL DEFAULT '0', "___remote_decSize" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_0b60ebb3aa0065f10b0616c1171" UNIQUE ("date"), CONSTRAINT "PK_e7ec0de057c77c40fc8d8b62151" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_0b60ebb3aa0065f10b0616c117" ON "__chart_day__drive"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart__per_user_reaction" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___local_count" smallint NOT NULL DEFAULT '0', "___remote_count" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_229a41ad465f9205f1f57032910" UNIQUE ("date", "group"), CONSTRAINT "PK_984f54dae441e65b633e8d27a7f" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_229a41ad465f9205f1f5703291" ON "__chart__per_user_reaction"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__per_user_reaction" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___local_count" smallint NOT NULL DEFAULT '0', "___remote_count" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_d54b653660d808b118e36c184c0" UNIQUE ("date", "group"), CONSTRAINT "PK_8af24e2d51ff781a354fe595eda" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_d54b653660d808b118e36c184c" ON "__chart_day__per_user_reaction"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__per_user_following" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___local_followings_total" integer NOT NULL DEFAULT '0', "___local_followings_inc" smallint NOT NULL DEFAULT '0', "___local_followings_dec" smallint NOT NULL DEFAULT '0', "___local_followers_total" integer NOT NULL DEFAULT '0', "___local_followers_inc" smallint NOT NULL DEFAULT '0', "___local_followers_dec" smallint NOT NULL DEFAULT '0', "___remote_followings_total" integer NOT NULL DEFAULT '0', "___remote_followings_inc" smallint NOT NULL DEFAULT '0', "___remote_followings_dec" smallint NOT NULL DEFAULT '0', "___remote_followers_total" integer NOT NULL DEFAULT '0', "___remote_followers_inc" smallint NOT NULL DEFAULT '0', "___remote_followers_dec" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_b77d4dd9562c3a899d9a286fcd7" UNIQUE ("date", "group"), CONSTRAINT "PK_85bb1b540363a29c2fec83bd907" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_b77d4dd9562c3a899d9a286fcd" ON "__chart__per_user_following"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__per_user_following" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___local_followings_total" integer NOT NULL DEFAULT '0', "___local_followings_inc" smallint NOT NULL DEFAULT '0', "___local_followings_dec" smallint NOT NULL DEFAULT '0', "___local_followers_total" integer NOT NULL DEFAULT '0', "___local_followers_inc" smallint NOT NULL DEFAULT '0', "___local_followers_dec" smallint NOT NULL DEFAULT '0', "___remote_followings_total" integer NOT NULL DEFAULT '0', "___remote_followings_inc" smallint NOT NULL DEFAULT '0', "___remote_followings_dec" smallint NOT NULL DEFAULT '0', "___remote_followers_total" integer NOT NULL DEFAULT '0', "___remote_followers_inc" smallint NOT NULL DEFAULT '0', "___remote_followers_dec" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_e4849a3231f38281280ea4c0eee" UNIQUE ("date", "group"), CONSTRAINT "PK_68ce6b67da57166da66fc8fb27e" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_e4849a3231f38281280ea4c0ee" ON "__chart_day__per_user_following"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__per_user_drive" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___totalCount" integer NOT NULL DEFAULT '0', "___totalSize" integer NOT NULL DEFAULT '0', "___incCount" smallint NOT NULL DEFAULT '0', "___incSize" integer NOT NULL DEFAULT '0', "___decCount" smallint NOT NULL DEFAULT '0', "___decSize" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_30bf67687f483ace115c5ca6429" UNIQUE ("date", "group"), CONSTRAINT "PK_d0ef23d24d666e1a44a0cd3d208" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_30bf67687f483ace115c5ca642" ON "__chart__per_user_drive"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart_day__per_user_drive" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "group" character varying(128) NOT NULL, "___totalCount" integer NOT NULL DEFAULT '0', "___totalSize" integer NOT NULL DEFAULT '0', "___incCount" smallint NOT NULL DEFAULT '0', "___incSize" integer NOT NULL DEFAULT '0', "___decCount" smallint NOT NULL DEFAULT '0', "___decSize" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_62aa5047b5aec92524f24c701d7" UNIQUE ("date", "group"), CONSTRAINT "PK_1ae135254c137011645da7f4045" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_62aa5047b5aec92524f24c701d" ON "__chart_day__per_user_drive"  ("date", "group") ;--> statement-breakpoint
CREATE TABLE "__chart__ap_request" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___deliverFailed" integer NOT NULL DEFAULT '0', "___deliverSucceeded" integer NOT NULL DEFAULT '0', "___inboxReceived" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_e56f4beac5746d44bc3e19c80d0" UNIQUE ("date"), CONSTRAINT "PK_56a25cd447c7ee08876b3baf8d8" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_e56f4beac5746d44bc3e19c80d" ON "__chart__ap_request"  ("date") ;--> statement-breakpoint
CREATE TABLE "__chart_day__ap_request" ("id" SERIAL NOT NULL, "date" integer NOT NULL, "___deliverFailed" integer NOT NULL DEFAULT '0', "___deliverSucceeded" integer NOT NULL DEFAULT '0', "___inboxReceived" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_a848f66d6cec11980a5dd595822" UNIQUE ("date"), CONSTRAINT "PK_9318b49daee320194e23f712e69" PRIMARY KEY ("id"));--> statement-breakpoint
CREATE UNIQUE INDEX "IDX_a848f66d6cec11980a5dd59582" ON "__chart_day__ap_request"  ("date") ;--> statement-breakpoint

-- 誕生日の月日部分を取り出す関数インデックス用の関数。drizzle-ormにストアドプロシージャの概念が無く生成不可。
CREATE OR REPLACE FUNCTION get_birthday_date(birthday TEXT) RETURNS SMALLINT AS $$ BEGIN RETURN CAST((SUBSTR(birthday, 6, 2) || SUBSTR(birthday, 9, 2)) AS SMALLINT); END; $$ LANGUAGE plpgsql IMMUTABLE;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "IDX_USERPROFILE_BIRTHDAY_DATE" ON "user_profile" (get_birthday_date("birthday"));--> statement-breakpoint

-- pg_trgm拡張機能とtrigram GINインデックス。CREATE EXTENSIONはdrizzle-kitに対応する概念が無く生成不可。
-- 式はクエリ側と完全一致させること: note lower("text"), user "name"/"usernameLower", user_profile "description"
SET statement_timeout = 0;--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "IDX_NOTE_TEXT_TRGM" ON "note" USING gin (lower("text") gin_trgm_ops) WITH (fastupdate = off);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "IDX_USER_NAME_TRGM" ON "user" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "IDX_USER_USERNAME_LOWER_TRGM" ON "user" USING gin ("usernameLower" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "IDX_USER_PROFILE_DESCRIPTION_TRGM" ON "user_profile" USING gin ("description" gin_trgm_ops);--> statement-breakpoint

-- usernameLowerへの前方一致検索用opclassインデックス。同一カラムに既存の通常btreeと共存させるため、
-- drizzle-kitでの差分検出の安定性が未検証なためschema.tsには載せず、ここで直接管理する。
CREATE INDEX IF NOT EXISTS "IDX_USER_USERNAME_LOWER_PATTERN" ON "user" ("usernameLower" varchar_pattern_ops);--> statement-breakpoint

-- drive_fileの容量集計用カバリングインデックス(INCLUDE句)。drizzle-ormのIndexConfig型にINCLUDEが無く生成不可。
CREATE INDEX IF NOT EXISTS "IDX_DRIVE_FILE_USER_ID_SIZE" ON "drive_file" ("userId") INCLUDE ("size") WHERE "isLink" = FALSE;--> statement-breakpoint
