-- TABLE: meta
CREATE TABLE "public"."meta" (
    "id" character varying(32) NOT NULL,
    "rootUserId" character varying(32),
    "name" character varying(1024),
    "shortName" character varying(64),
    "description" character varying(1024),
    "maintainerName" character varying(1024),
    "maintainerEmail" character varying(1024),
    "disableRegistration" boolean DEFAULT true NOT NULL,
    "langs" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "pinnedUsers" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "hiddenTags" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "blockedHosts" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "sensitiveWords" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "prohibitedWords" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "prohibitedWordsForNameOfUser" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "silencedHosts" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "mediaSilencedHosts" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "themeColor" character varying(1024),
    "mascotImageUrl" character varying(1024),
    "bannerUrl" character varying(1024),
    "backgroundImageUrl" character varying(1024),
    "logoImageUrl" character varying(1024),
    "iconUrl" character varying(1024),
    "app192IconUrl" character varying(1024),
    "app512IconUrl" character varying(1024),
    "serverErrorImageUrl" character varying(1024),
    "notFoundImageUrl" character varying(1024),
    "infoImageUrl" character varying(1024),
    "cacheRemoteFiles" boolean DEFAULT false NOT NULL,
    "cacheRemoteSensitiveFiles" boolean DEFAULT true NOT NULL,
    "emailRequiredForSignup" boolean DEFAULT false NOT NULL,
    "enableHcaptcha" boolean DEFAULT false NOT NULL,
    "hcaptchaSiteKey" character varying(1024),
    "hcaptchaSecretKey" character varying(1024),
    "enableCap" boolean DEFAULT false CONSTRAINT "meta_enableMcaptcha_not_null" NOT NULL,
    "enableRecaptcha" boolean DEFAULT false NOT NULL,
    "recaptchaSiteKey" character varying(1024),
    "recaptchaSecretKey" character varying(1024),
    "enableTurnstile" boolean DEFAULT false NOT NULL,
    "turnstileSiteKey" character varying(1024),
    "turnstileSecretKey" character varying(1024),
    "enableTestcaptcha" boolean DEFAULT false NOT NULL,
    "sensitiveMediaDetection" "public"."meta_sensitivemediadetection_enum" DEFAULT 'none'::"public"."meta_sensitivemediadetection_enum" NOT NULL,
    "sensitiveMediaDetectionSensitivity" "public"."meta_sensitivemediadetectionsensitivity_enum" DEFAULT 'medium'::"public"."meta_sensitivemediadetectionsensitivity_enum" NOT NULL,
    "setSensitiveFlagAutomatically" boolean DEFAULT false NOT NULL,
    "enableSensitiveMediaDetectionForVideos" boolean DEFAULT false NOT NULL,
    "sensitiveMediaDetectionApiUrl" character varying(1024),
    "sensitiveMediaDetectionApiKey" character varying(1024),
    "sensitiveMediaDetectionTimeout" integer DEFAULT 60000 NOT NULL,
    "sensitiveMediaDetectionMaxImagesPerRequest" integer DEFAULT 4 NOT NULL,
    "enableEmail" boolean DEFAULT false NOT NULL,
    "email" character varying(1024),
    "smtpSecure" boolean DEFAULT false NOT NULL,
    "smtpHost" character varying(1024),
    "smtpPort" integer,
    "smtpUser" character varying(1024),
    "smtpPass" character varying(1024),
    "enableServiceWorker" boolean DEFAULT false NOT NULL,
    "swPublicKey" character varying(1024),
    "swPrivateKey" character varying(1024),
    "deeplAuthKey" character varying(1024),
    "deeplIsPro" boolean DEFAULT false NOT NULL,
    "termsOfServiceUrl" character varying(1024),
    "repositoryUrl" character varying(1024) DEFAULT 'https://github.com/haru0416-dev/misskey'::character varying,
    "feedbackUrl" character varying(1024) DEFAULT 'https://github.com/haru0416-dev/misskey/issues/new'::character varying,
    "impressumUrl" character varying(1024),
    "privacyPolicyUrl" character varying(1024),
    "inquiryUrl" character varying(1024),
    "defaultLightTheme" character varying(8192),
    "defaultDarkTheme" character varying(8192),
    "useObjectStorage" boolean DEFAULT false NOT NULL,
    "objectStorageBucket" character varying(1024),
    "objectStoragePrefix" character varying(1024),
    "objectStorageBaseUrl" character varying(1024),
    "objectStorageEndpoint" character varying(1024),
    "objectStorageRegion" character varying(1024),
    "objectStorageAccessKey" character varying(1024),
    "objectStorageSecretKey" character varying(1024),
    "objectStoragePort" integer,
    "objectStorageUseSSL" boolean DEFAULT true NOT NULL,
    "objectStorageUseProxy" boolean DEFAULT true NOT NULL,
    "objectStorageSetPublicRead" boolean DEFAULT false NOT NULL,
    "objectStorageS3ForcePathStyle" boolean DEFAULT true NOT NULL,
    "enableIpLogging" boolean DEFAULT false NOT NULL,
    "enableActiveEmailValidation" boolean DEFAULT true NOT NULL,
    "enableVerifymailApi" boolean DEFAULT false NOT NULL,
    "verifymailAuthKey" character varying(1024),
    "enableTruemailApi" boolean DEFAULT false NOT NULL,
    "truemailInstance" character varying(1024),
    "truemailAuthKey" character varying(1024),
    "enableChartsForRemoteUser" boolean DEFAULT true NOT NULL,
    "enableChartsForFederatedInstances" boolean DEFAULT true NOT NULL,
    "enableStatsForFederatedInstances" boolean DEFAULT true NOT NULL,
    "enableServerMachineStats" boolean DEFAULT false NOT NULL,
    "enableIdenticonGeneration" boolean DEFAULT true NOT NULL,
    "policies" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "serverRules" character varying(280)[] DEFAULT '{}'::character varying[] NOT NULL,
    "manifestJsonOverride" character varying(8192) DEFAULT '{}'::character varying NOT NULL,
    "bannedEmailDomains" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "preservedUsernames" character varying(1024)[] DEFAULT '{admin,administrator,root,system,maintainer,host,mod,moderator,owner,superuser,staff,auth,i,me,everyone,all,mention,mentions,example,user,users,account,accounts,official,help,helps,support,supports,info,information,informations,announce,announces,announcement,announcements,notice,notification,notifications,dev,developer,developers,tech,misskey}'::character varying[] NOT NULL,
    "enableFanoutTimeline" boolean DEFAULT true NOT NULL,
    "enableFanoutTimelineDbFallback" boolean DEFAULT true NOT NULL,
    "perLocalUserUserTimelineCacheMax" integer DEFAULT 300 NOT NULL,
    "perRemoteUserUserTimelineCacheMax" integer DEFAULT 100 NOT NULL,
    "perUserHomeTimelineCacheMax" integer DEFAULT 300 NOT NULL,
    "perUserListTimelineCacheMax" integer DEFAULT 300 NOT NULL,
    "notesPerOneAd" integer DEFAULT 0 NOT NULL,
    "urlPreviewEnabled" boolean DEFAULT true NOT NULL,
    "urlPreviewAllowRedirect" boolean DEFAULT true NOT NULL,
    "urlPreviewTimeout" integer DEFAULT 10000 NOT NULL,
    "urlPreviewMaximumContentLength" bigint DEFAULT 10485760 NOT NULL,
    "urlPreviewRequireContentLength" boolean DEFAULT false NOT NULL,
    "urlPreviewSummaryProxyUrl" character varying(1024),
    "urlPreviewUserAgent" character varying(1024),
    "federation" character varying(128) DEFAULT 'none'::character varying NOT NULL,
    "federationHosts" character varying(1024)[] DEFAULT '{}'::character varying[] NOT NULL,
    "ugcVisibilityForVisitor" character varying(128) DEFAULT 'local'::character varying NOT NULL,
    "googleAnalyticsMeasurementId" character varying(64),
    "deliverSuspendedSoftware" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "singleUserMode" boolean DEFAULT false NOT NULL,
    "proxyRemoteFiles" boolean DEFAULT true NOT NULL,
    "signToActivityPubGet" boolean DEFAULT true NOT NULL,
    "allowExternalApRedirect" boolean DEFAULT true NOT NULL,
    "enableRemoteNotesCleaning" boolean DEFAULT false NOT NULL,
    "remoteNotesCleaningMaxProcessingDurationInMinutes" integer DEFAULT 60 NOT NULL,
    "remoteNotesCleaningExpiryDaysForEachNotes" integer DEFAULT 90 NOT NULL,
    "showRoleBadgesOfRemoteUsers" boolean DEFAULT false NOT NULL,
    "clientOptions" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "signupRateLimitMinIntervalSeconds" integer DEFAULT 0 NOT NULL,
    "signupRateLimitMaxPerHour" integer DEFAULT 0 NOT NULL,
    "translatorProvider" character varying(32) DEFAULT 'deepl'::character varying NOT NULL,
    "libreTranslateApiUrl" character varying(1024),
    "libreTranslateApiKey" character varying(1024),
    "urlPreviewSensitiveList" character varying(3072)[] DEFAULT '{}'::character varying[] NOT NULL,
    "capSiteKey" character varying(1024),
    "capSecretKey" character varying(1024),
    "capInstanceUrl" character varying(1024)
);

-- CONSTRAINT: meta meta_pkey
ALTER TABLE ONLY "public"."meta"
    ADD CONSTRAINT "meta_pkey" PRIMARY KEY ("id");
