configVersion: 2

instance:
  url: http://misskey.local
  setupPassword:
    plainText: example_password_please_change_this_or_you_will_get_hacked

server:
  listen:
    tcp:
      address: 127.0.0.1
      port: 61812

database:
  primary:
    host: 127.0.0.1
    port: 54312
    name: test-misskey
    user: postgres
    password:
      plainText: ''

valkey:
  connections:
    primary:
      host: 127.0.0.1
      port: 56312

outboundNetwork:
  privateNetworkAccess:
    allowedNetworks:
      - 127.0.0.1/32
