/*
	This file is automatically generated by scripts/gen-pkg-ts.js.
	DO NOT edit this file. To change it's behavior, edit scripts/gen-pkg-ts.js instead.
*/
export const pkg = {
	"version": "1.2.1"
} as const;
