name: API report (misskey.js)

on:
  push:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
  pull_request:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version
      - name: Cache bun install cache
        uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --bun --filter misskey-js build

      - name: Check files
        run: ls packages/misskey-js/built

      - name: API report
        run: bun run --bun --filter misskey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/misskey-js/temp/misskey-js.api.md
