name: API report (misskey.js)

on:
  push:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
  pull_request:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --bun --filter misskey-js build

      - name: Check files
        run: ls packages/misskey-js/built

      - name: API report
        run: bun run --bun --filter misskey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/misskey-js/temp/misskey-js.api.md
