name: Check the description in CHANGELOG.md

on:
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout head
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Checkout base
        run: |
          mkdir _base
          cp -r .git _base/.git
          cd _base
          git fetch --depth 1 origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }} CHANGELOG.md

      - name: Copy to Checker directory for CHANGELOG-base.md
        run: cp _base/CHANGELOG.md scripts/changelog-checker/CHANGELOG-base.md
      - name: Copy to Checker directory for CHANGELOG-head.md
        run: cp CHANGELOG.md scripts/changelog-checker/CHANGELOG-head.md
      - name: diff
        continue-on-error: true
        run: diff -u CHANGELOG-base.md CHANGELOG-head.md
        working-directory: scripts/changelog-checker

      - name: Test Checker
        run: bun run --bun --filter changelog-checker test

      - name: Run Checker
        run: bun run run
        working-directory: scripts/changelog-checker
