name: Lint (locale)

on:
  push:
    paths:
      - packages/i18n/**
      - locales/**
      - .github/workflows/locale.yml
  pull_request:
    paths:
      - packages/i18n/**
      - locales/**
      - .github/workflows/locale.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  locale_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version
      - name: Cache bun install cache
        uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - run: bun install --frozen-lockfile
      - run: bun run --bun --filter i18n build
      - name: Verify Locales
        working-directory: ./packages/i18n
        run: bun run verify
