# This workflow installs Bun dependencies, builds misskey-js, and runs tests.

name: Test (misskey.js)

on:
  push:
    branches: [develop]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
  pull_request:
    branches: [develop]
    paths:
      - packages/misskey-js/**
      - .github/workflows/test-misskey-js.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit tests (misskey.js)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check bun.lock
        run: git diff --exit-code bun.lock

      - name: Build
        run: bun run --bun --filter misskey-js build

      - name: Test
        run: bun run --bun --filter misskey-js test
        env:
          CI: true
