name: Test (federation)

on:
  push:
    branches:
      - master
      - develop
    paths:
      - packages/backend/**
      - packages/misskey-js/**
      - .github/workflows/test-federation.yml
  pull_request:
    paths:
      - packages/backend/**
      - packages/misskey-js/**
      - .github/workflows/test-federation.yml
  workflow_dispatch:

jobs:
  test:
    name: Federation test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version-file: .bun-version
      - name: Install FFmpeg
        run: |
          sudo apt install -y ffmpeg
      - name: Build Misskey
        run: |
          bun install --frozen-lockfile
          bun run build
      - name: Setup
        run: |
          echo "BUN_VERSION=$(cat .bun-version)" >> $GITHUB_ENV
          cd packages/backend/test-federation
          bash ./setup.sh
          sudo chmod 644 ./certificates/*.test.key
      - name: Start servers
        id: start_servers
        continue-on-error: true
        # https://github.com/docker/compose/issues/1294#issuecomment-374847206
        run: |
          cd packages/backend/test-federation
          docker compose up -d --scale tester=0
      - name: Print start_servers error
        if: ${{ steps.start_servers.outcome == 'failure' }}
        run: |
          cd packages/backend/test-federation
          docker compose logs | tail -n 300
          exit 1
      - name: Test
        run: |
          cd packages/backend/test-federation
          docker compose run --no-deps tester
      - name: Log
        if: always()
        run: |
          cd packages/backend/test-federation
          docker compose logs
      - name: Stop servers
        if: always()
        run: |
          cd packages/backend/test-federation
          docker compose down
